---
# Configure the locale.

- name: uncomment the en_GB.UTF-8 line
  lineinfile: dest=/etc/locale.gen
              regexp="^#?en_GB.UTF-8 UTF-8$"
              line="en_GB.UTF-8 UTF-8"
              state=present
  register: locale

- name: generate the locale files
  command: locale-gen
  when: locale|changed  
