---
# Install and configure vim.

- name: install vim
  pacman: name=vim
          state=present

- name: add the .vimrc file to the user's home directory
  copy: src=vimrc
        dest=/home/{{ user_name }}/.vimrc
